$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$src = Join-Path $scriptDir "start_silent.vbs"
$dst = Join-Path $env:APPDATA "Microsoft\Windows\Start Menu\Programs\Startup\FileVault.vbs"
Copy-Item $src -Destination $dst -Force
Write-Host ""
Write-Host "========================================"
Write-Host "  Auto-start Installed Successfully!"
Write-Host "========================================"
Write-Host ""
Write-Host "File copied to: $dst"
Write-Host ""
Write-Host "On next boot:"
Write-Host "  1. Server will start automatically"
Write-Host "  2. Browser will open http://localhost:8888"
Write-Host ""
